Bugfix/scan 543 minor bugs
UniqueNetwork/uniq-blockexplorer pull request #353
Opened 2023-01-12 07:25 UTC by drgoshm

2023-01-13 12:15 UTC, SergeyOkishev requested changes

2023-01-13 12:15 UTC, SergeyOkishev commented on src/pages/Tokens/components/AttributesFilter/index.tsx
> +                    ((
прорефачь плз, оно и до этого было нечитаемо, а сейчас даже смотреть страшно :( 

хотяб просто на функции разбить, может даже файли утилит бахнуть рядом в этой же папке

2023-01-16 07:59 UTC, drgoshm commented on src/pages/Tokens/components/AttributesFilter/index.tsx
> +                    ((
fixed

2023-01-16 08:28 UTC, SergeyOkishev approved these changes

2023-01-16 08:28 UTC, merged